language: node_js
node_js:
  - node
script: npm run build
before_script:
  - sed -i "s/GIT_CREDENTIALS/${GIT_CREDENTIALS}/" _config.yml
deploy:
  - provider: script
    script: npm run deploy
    on:
      all_branches: true
