fancybox: true
show_category_count: true

menu: 
  - page: Home
    directory: .
  - page: Archive
    directory: archives/
  - page: About
    directory: about/

widgets:
  - category
  - tag
  - links

links:
  - title: dedicatus545
    url: //cnblogs.com/dedicatus545
  - title: sshockwave
    url: https://blog.sshockwave.net
